# Generated by Django 3.2.9 on 2021-12-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211129_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
