# Generated by Django 3.2.9 on 2021-11-29 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0002_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(to='products.ProductItem', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
