# Generated by Django 3.2.9 on 2021-11-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Заказ продукта', 'verbose_name_plural': 'Заказ продуктов'},
        ),
    ]
