# Generated by Django 3.2.9 on 2021-11-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20211126_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_sum',
        ),
    ]
