# Generated by Django 3.2.9 on 2021-11-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cartitem_total_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар корзины', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
