# Generated by Django 3.2.9 on 2021-11-29 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0006_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая цена корзины'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item_cart', to='products.productitem', verbose_name='Продукт'),
        ),
    ]
